/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-background": "#1b1b23",
        "outline-variant": "#c7c4d7",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary": "#904900",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-primary": "#c0c1ff",
        "secondary-fixed": "#e2dfff",
        "surface-tint": "#494bd6",
        "tertiary-container": "#b55d00",
        "primary-fixed-dim": "#c0c1ff",
        "background": "#fcf8ff",
        "surface-container": "#efecf8",
        "on-primary-fixed": "#07006c",
        "primary-container": "#6063ee",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4b41e1",
        "on-tertiary-fixed": "#301400",
        "on-primary-container": "#fffbff",
        "surface-container-highest": "#e4e1ed",
        "surface-dim": "#dbd8e4",
        "primary": "#4648d4",
        "inverse-on-surface": "#f2effb",
        "surface-container-high": "#e9e6f3",
        "outline": "#767586",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#1b1b23",
        "on-secondary-fixed-variant": "#3323cc",
        "on-tertiary-container": "#fffbff",
        "surface-variant": "#e4e1ed",
        "secondary-fixed-dim": "#c3c0ff",
        "secondary-container": "#645efb",
        "inverse-surface": "#303038",
        "on-surface-variant": "#464554",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary-fixed": "#0f0069",
        "primary-fixed": "#e1e0ff",
        "surface-bright": "#fcf8ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f2fe",
        "surface": "#fcf8ff",
        "tertiary-fixed": "#ffdcc5"
      },
      "spacing": {
        "base-unit": "4px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "stack-lg": "32px",
        "stack-md": "16px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "display-countdown": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-countdown": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
